name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy Application
        run: |
          echo "Deployment process starts here"
          
          # Fetch and reset to latest code
          git fetch origin main
          git reset --hard origin/main
          
          # Build and push Docker image
          docker build -t your-username/fastapi-app .
          docker push your-username/fastapi-app
          
          # Optional: Run additional deployment steps here
